# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
        # Base the cache on the session, simplesaml cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^SimpleSAML/']
    tls:
        min_version: TLSv1.2
        strict_transport_security:
            enabled: true
            include_subdomains: true
            preload: true

# strip www prefix
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

# force SSL
"http://{default}/":
   type: redirect
   to: "https://{default}/"

# force SSL, strip www prefix
"http://www.{default}/":
   type: redirect
   to: "https://{default}/"
